### PR TITLE
fix grammar in README

### PR DESCRIPTION
**Pull request by akshayrs3**
## PR Title

The purpose of this Pull Request is to fix the readme file and make it grammatically correct for readers

## Description
Added missing words and made it more grammatically accurate for readers and contributors. 

## How you solved
Fixed grammar in the readme file.

### Screenshots
 N/A

##  Checklist
- [ YES ] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [ YES ] I have tested in local Environment.
- [ YES ] I have made the fix as per issue converstaion
- [ YES ] I have starred the repository ⭐

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
Hi @akshayrs3 ,

Please make a bug issue for this PR. That will help us to keep track of changes done.

Will review these changes

**Comment by akshayrs3** [comment]
Linking issue
[https://github.com/jsvigneshkanna/tailwind_ui_components/issues/23]

**Comment by jsvigneshkanna** [comment]
@akshayrs3 ,
can you please pull latest readme changes and run one final grammar check as these as some conflicts

**Comment by akshayrs3** [comment]
done

**Review by jsvigneshkanna — APPROVED** [review]

**Comment by jsvigneshkanna** [comment]
@akshayrs3 Looking good, Thank you

BTW dont forget to star this project to make it cooler and check for other issues too

**Pull request merged**
