### PR TITLE
Update navbar.js

### LINKED ISSUE #55: [Bug]: nav logo not redirecting
### Bug Title

Non redirecting logo

### Description of BUG

Logo in navbar should redirect to homepage on click

### Reporduction URL of bug

Homepage

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

Nill

### Are you taking this issue fix

No

### PR DESCRIPTION
**Pull request by Ved142**
Added the functionality of redirecting to home on clicking nav logo.

## PR Title
The purpose of this Pull Request is to fix #55 

## Description
This fix will ensure that whenever a user clicks on navbar logo he/she will be directed to the homepage.

## How you solved
To Solve this problem I use Routers and onClick event. Whenever a person click on navbar logo, the onClick event will be fired and the user will be directed to home route.

### Screenshots

https://user-images.githubusercontent.com/78460491/196510015-0ec3b5ff-4b4b-4202-84a4-25b55947f1a4.mp4

  

##  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
@Ved142 
Great works, working as expected in preview deployment
Merging your changes

Also take a look on other issues like footer,new page creations too

**Comment by Ved142** [comment]
Hey @jsvigneshkanna, please add hacktoberfest tag on my request so that it get accepted in Hacktoberfest 2022. Thanks 😄!!

**Comment by jsvigneshkanna** [comment]
@Ved142 , didnt it counted on hacktoberfest, did you checked your profile? What s the status now?

**Comment by Ved142** [comment]
Really sorry for disturbing you @jsvigneshkanna I just somehow missed it. I checked my profile and it's there. Sorry again..

**Comment by jsvigneshkanna** [comment]
No problem buddy @Ved142 
It happens 😁
Btw, if you want to contribute more, please check for open issues

**Pull request merged**
