### PR TITLE
added a card with button using tailwind css

### PR DESCRIPTION
**Pull request by saroshfarhan**
## PR Title
Card with button for [issue](https://github.com/jsvigneshkanna/tailwind_ui_components/issues/56)

## Description
This PR adds a new codepen section which contains code snippet for a card container with user profile and a button to message.

## How you solved
Just added a card and a message button using tailwind CSS

### Screenshots

Screenshot 2022-10-18 at 11 22 49 PM

##  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
@saroshfarhan 

Perfect 💯 , preview looks good, merging your change

**Comment by jsvigneshkanna** [comment]
@saroshfarhan 
Also if can change the allignement/style of image and card please raise seperate PRs. For those too

**Comment by saroshfarhan** [comment]
Thank you @jsvigneshkanna !!

**Comment by saroshfarhan** [comment]
> @saroshfarhan Also if can change the allignement/style of image and card please raise seperate PRs. For those too

Sure, will try and make it more appealing. Thank you for the suggestion!🚀

**Pull request merged**
