### PR TITLE
responsive navbar

### LINKED ISSUE #33: [Bug]: Unresponsive navbar
### Bug Title

Unresponsive navbar

### Description of BUG

Navbar is unresponsive on mobile devices.

### Reporduction URL of bug

_No response_

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

tailwind-comp

### Are you taking this issue fix

Yes

### PR DESCRIPTION
**Pull request by chibuike-19**
## PR Title

The purpose of this Pull Request is to fix #33 

## Description
Made navbar responsive on mobile devices.

  

##  Checklist
- [ ] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [ ] I have tested in local Environment.
- [ ] I have made the fix as per issue converstaion

responsive-tailwind

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
@chibuike-19 
Can you please check why pages are not loading when clicked in nav bar

**Comment by jsvigneshkanna** [comment]
@chibuike-19 
Reverse merging and try the changes on top latest master branch

**Comment by chibuike-19** [comment]
> @chibuike-19 Reverse merging and try the changes on top latest master branch


Alright, trying to resolve the conflicts

**Comment by chibuike-19** [comment]
Why are the checks failing? looks alright to me.......I've resolved all existing conflicts tho

**Comment by jsvigneshkanna** [comment]
@chibuike-19 
Resolved the issue and merged your changes

Please check other unassigned issue !

Appreciate that!

**Pull request merged**
