### PR TITLE
[FEATURE]: Brand card in tailwindcss

### LINKED ISSUE #113: [FEATURE]: Brand card in tailwindcss
### Description

**Need to create code for Brand card feature card  as per below image.**

- The final code should be placed under path `tailwind_components/feature_cards` with file name as `brand_card.jsx`
- The file as to be imported to `tailwind_components/feature_cards/collection.js` file as per example and added to the `featureCardColletion` list
- Post these process, go to components tab (components/feature_cards) in website and check whether the codepen is updated

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

image

### Are you taking this fetaure implementaion

no

### PR DESCRIPTION
**Pull request by Anuran12**
## PR Title

The purpose of this Pull Request is to fix #113 

## Description

added brand card

## How you solved

At first i made the component in [Tailwind Playgrounds](https://play.tailwindcss.com/)
then i added that into the file

### Screenshots

  
image

##  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

### CODE REVIEW

**Comment by Anuran12** [comment]
@jsvigneshkanna Done

**Comment by jsvigneshkanna** [comment]
@Anuran12 , please text align center 

image

**Comment by Anuran12** [comment]
@jsvigneshkanna  done

**Comment by jsvigneshkanna** [comment]
Great @Anuran12 ,

please check other issues too, you are becoming one the best contributors to our project

**Pull request merged**
