### PR TITLE
Fixes Bug Issue No #267

### LINKED ISSUE #267: [Bug]: Responsiveness
### Bug Title

Responsiveness Issue

### Description of BUG

Social icons are hiding in responsiveness.

Kindly assign me this issue.

### Reporduction URL of bug

_No response_

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

image

### Are you taking this issue fix

yes

### PR DESCRIPTION
**Pull request by AmanJain18**
## PR Title
The purpose of this Pull Request is to fix #267
Responsiveness Issue
Issue Refix for view Port <900px and FAQs page

## Description
Social icons are hiding in responsiveness (<900px viewport).

## How you solved
Modifying socialbutton file

### Screenshots
image

##  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

@jsvigneshkanna Kindly review and merge the PR ✌️🙂

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
Only keep github and linkedin icons on mobile or width <900px. Check the preview in mobile screen it dont look good

**Comment by jsvigneshkanna** [comment]
Don't make unnecessary changes that don't mention in the issue ticket. Just display GitHub and LinkedIn social icons for screens less than 900px width and add some padding for them (p-4)

Undo other file changes.

**Comment by AmanJain18** [comment]
> Only keep github and linkedin icons on mobile or width <900px. Check the preview in mobile screen it dont look good

Okay, Will fix it

**Comment by AmanJain18** [comment]
> Don't make unnecessary changes that don't mention in the issue ticket. Just display GitHub and LinkedIn social icons for screens less than 900px width and add some padding for them (p-4)
> 
> Undo other file changes. 

I have added all social icon on faqs page, Should I keep that or remove it completely
Earlier all pages were having social icon except FAQs Page...

**Comment by jsvigneshkanna** [comment]
let faq page don't have social icons

**Comment by AmanJain18** [comment]
I have Re fIx The Issue, just check and review it ✌️

**Pull request merged**
