### PR TITLE
added privacy policy page and component

### LINKED ISSUE #214: Create new privacy policy page in nextjs
### Feature Title

Privacy policy

### Description

- Need to create a new privacy policy component which has the below points, and import that component to a new page with a navbar and footer
- The new page shouldn't have a loader
- New page should be styled only with tailwindcss
- the background color should be of license page and same text colour
- new page should be linked to footer link

Points to be covered,

1. Collection of non-personal information
When you visit the Website our servers automatically record information that your browser sends. This data may include information such as your device's IP address, browser type and version, operating system type and version, language preferences or the webpage you were visiting before you came to our Website, pages of our Website that you visit, the time spent on those pages, information you search for on our Website, access times and dates, and other statistics.

2. Use and processing of collected information
Any of the information we collect from you may be used to personalize your experience; improve our Website; improve customer service; process transactions; send notification emails such as password reminders, updates, etc; and operate our Website. Non-Personal Information collected is used only to identify potential cases of abuse and establish statistical information regarding Website usage. This statistical information is not otherwise aggregated in such a way that would identify any particular user of the system.

We may process Personal Information related to you if one of the following applies: (i) You have given their consent for one or more specific purposes. Note that under some legislations we may be allowed to process information until you object to such processing (by opting out), without having to rely on consent or any other of the following legal bases below. This, however, does not apply, whenever the processing of Personal Information is subject to European data protection law; (ii) Provision of information is necessary for the performance of an agreement with you and/or for any pre-contractual obligations thereof; (ii) Processing is necessary for compliance with a legal obligation to which you are subject; (iv) Processing is related to a task that is carried out in the public interest or in the exercise of official authority vested in us; (v) Processing is necessary for the purposes of the legitimate interests pursued by us or by a third party. In any case, we will be happy to clarify the specific legal basis that applies to the processing, and in particular whether the provision of Personal Data is a statutory or contractual requirement, or a requirement necessary to enter into a contract.

3.Privacy of children
We do not knowingly collect any Personal Information from children under the age of 13. If you are under the age of 13, please do not submit any Personal Information through our Website. We encourage parents and legal guardians to monitor their children's Internet usage and to help enforce this Policy by instructing their children never to provide Personal Information through our Website without their permission. If you have reason to believe that a child under the age of 13 has provided Personal Information to us through our Website, please contact us.

4.Newsletters
We offer electronic newsletters which you may voluntarily subscribe to. You may choose to stop receiving our newsletter or marketing emails by following the unsubscribe instructions included in these emails or by contacting us. However, you will continue to receive essential transactional emails

5.Links to other websites
Our Website contains links to other websites that are not owned or controlled by us. Please be aware that we are not responsible for the privacy practices of such other websites or third parties. We encourage you to be aware when you leave our Website and to read the privacy statements of each and every website that may collect Personal Information.

Also add last updated date of privacy policy at top of page

### Motivation

Privacy policy will ensure use, by adhering to standard rules

### Issue Type

Backend

### Screenshot of the feature if done ?

Nill

### Are you taking this fetaure implementaion

No - up for grabs

### PR DESCRIPTION
**Pull request by SarveshPatil29**
## PR Title

The purpose of this Pull Request is to fix #214

## Description

I created one page for privacy policy and one component for privacy policy and added it to the page component

## How you solved

I followed the conventions used by other pages and designed the policy page by referring to those pages

### Screenshots

  
Screenshot 2022-10-24 at 10 52 49 AM
Screenshot 2022-10-24 at 10 53 20 AM

##  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

@jsvigneshkanna Please let me know if any changes are required.

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
@SarveshPatil29 add below styling to new component 
`md:px-40 px-4`

**Comment by jsvigneshkanna** [comment]
And in place of `'/"` please use `&apos;`

**Comment by SarveshPatil29** [comment]
> @SarveshPatil29 add below styling to new component `md:px-40 px-4`

@jsvigneshkanna it is already present in privacyPolicyComp.js

**Comment by jsvigneshkanna** [comment]
Great @SarveshPatil29 
Iwill resolve the deployment issue, please check other issues/feature

**Comment by SarveshPatil29** [comment]
> And in place of `'/"` please use `&apos;`

@jsvigneshkanna Can you please explain this? I am unable to comprehend.

**Comment by SarveshPatil29** [comment]
> Great @SarveshPatil29 Iwill resolve the deployment issue, please check other issues/feature

Thanks, @jsvigneshkanna.
Sure I will checkout other issues as well!

**Comment by jsvigneshkanna** [comment]
@SarveshPatil29 , There was small issue

We shouldnt use `'` in div/ p elements, instead we should use `&apos;` unicode

Resolved and merging your changes

**Comment by SarveshPatil29** [comment]
> @SarveshPatil29 , There was small issue
> 
> We shouldnt use `'` in div/ p elements, instead we should use `&apos;` unicode
> 
> Resolved and merging your changes

Ohh ohhk👍

**Pull request merged**
