### PR TITLE
Added stars/forks feature

### LINKED ISSUE #189: Add github forks/ stars widget in website homepage
### Feature Title

Add github forks/ stars widget

### Description

- We need to GitHub stars/ forks widget in homepage inside homebanner.js component
- It needs to position as displayed in below screenshot

### Motivation

Displaying Github forks/ stars in webpage would bring more audiences

### Issue Type

Backend

### Screenshot of the feature if done ?

image

### Are you taking this fetaure implementaion

Up for grabs

### PR DESCRIPTION
**Pull request by harsh0620**
## PR Title

The purpose of this Pull Request is to fix #189 

## Description
- Stars and Forks of the repo will be shown below the navbar

## How you solved
- Use github's Octokit/rest package to get repo details
- and swr package to update the details without refreshing
- One has to assign access token in .env as GITHUB_AUTH_TOKEN=<Github Access Token>
- For star and fork icon use react-icon package

### Screenshots
image

  

##  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
@harsh0620 , whose auth token is there in env file. Should i need to update that to mine?

**Comment by harsh0620** [comment]
@jsvigneshkanna , yes your auth token should be used here.

**Comment by jsvigneshkanna** [comment]
@harsh0620 , can you please check the conflicts ( i am not sure because those are in yarn and packages)

Also check for other open issues too

**Comment by harsh0620** [comment]
@jsvigneshkanna I try to resolve the conflicts by maintaining same code but its not resolving conflicts.
I think It will not create any problem as the change in package and yarn file is emerging as I installed two packages.
Please merge it as webapp is up and running fine.

**Comment by jsvigneshkanna** [comment]
@harsh0620 sure will check merge in sometime

Please check for other open issues

**Comment by jsvigneshkanna** [comment]
@harsh0620 ,
Can you raise new PR again with same changes ?

**Comment by harsh0620** [comment]
@jsvigneshkanna , I can but I only know to do this by writing same code after cloning the repo.
So I do that or you have any suggestion.

**Comment by jsvigneshkanna** [comment]
@harsh0620 
You can create new branch from master after pulling latest changes, then add same code

Push those

**Comment by jsvigneshkanna** [comment]
@harsh0620 ,
Let me know if any help needed

**Comment by harsh0620** [comment]
@jsvigneshkanna , the new PR has been generated.

**Pull request merged**
