### PR TITLE
Added License page

### LINKED ISSUE #190: New license page should be added
### Feature Title

New license page

### Description

- We need to add new page which reads the **_MIT LICENSE_** which we are using in this repo
- The page should be under new legal folder (NEXTJS routing)
- The new page URL should be /legal/license

1. The background color should be of component page (https://tailwindcsscomponents.vercel.app/components) and white text color with horizontal padding same as navbar
2. The page should be styled in tailwindCSS and needs to mobile responsive

For license content, refer https://github.com/jsvigneshkanna/tailwind_ui_components/blob/master/LICENSE

### Motivation

license page is must when we open this website to wide audience 

### Issue Type

Frontend

### Screenshot of the feature if done ?

nill

### Are you taking this fetaure implementaion

Up for grabs

### PR DESCRIPTION
**Pull request by mnosov622**
## PR Title
Added license page.

The purpose of this Pull Request is to fix #190 

## Description
Now license page is visible to the user from the footer link (License)

## How you solved
1. Created folder **legal**

2.  Wrote the license.js function 

3. Added LicenseContent component with the MIT license text from the [github repo](https://github.com/jsvigneshkanna/tailwind_ui_components).

### Screenshots
image
  

##  Checklist
- [x ] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
Great @mnosov622 

Please check for other issues which are open

**Comment by mnosov622** [comment]
Thank you @jsvigneshkanna !

I will :)

Are you going to merge this PR ?

**Comment by mnosov622** [comment]
@jsvigneshkanna , 

could you label this PR with hacktoberfest label, please ?

**Comment by jsvigneshkanna** [comment]
@mnosov622 didnt this counted to hacktoberfest?

**Comment by mnosov622** [comment]
I was hoping this could be for hacktoberfest :)

**Comment by jsvigneshkanna** [comment]
@mnosov622 welcome mate 🍻, check for other open issue

**Comment by mnosov622** [comment]
I will :)

You are so kind 😊

**Pull request merged**
