### PR TITLE
Style and Improve Faqs Sections

### PR DESCRIPTION
**Pull request by AmanJain18**
> ### Feature Title
> Improve UX when exploring FAQ section #280 
> 
## Description

**Tested for all Screen size and optimised**
> ### Issue Type
> Frontend
> 
> ### Screenshot of the feature if done ?
> 
image

> 
 ### Are you taking this fetaure implementaion
> Yes

##  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
We have some errors in deployement @AmanJain18 , can you check vercel logs. Seems issue with jquery

**Comment by AmanJain18** [comment]
I can't see anything on Vercel Gives Error 404

**Comment by jsvigneshkanna** [comment]
Will have a look. Meantime check for any bugs in website. 
Also check for https://github.com/jsvigneshkanna/leetcode_solved_programs

**Comment by AmanJain18** [comment]
For using font awesome remove cdn linl as it is  outdated and install its package

**Comment by jsvigneshkanna** [comment]
@AmanJain18 ,please raise issue for that

**Comment by AmanJain18** [comment]
> @AmanJain18 ,please raise issue for that

Fixed all issue and errors...

**Comment by jsvigneshkanna** [comment]
Will review and let you know @AmanJain18 
Thank you

**Comment by AmanJain18** [comment]
Did u check ?
If found any issues, let me know... @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
@AmanJain18 , can you please make the text and bg color in sync with website. New blue, yellow, green colors look odd

**Comment by jsvigneshkanna** [comment]
And also check why closing faq section isnt working

**Comment by AmanJain18** [comment]
> And also check why closing faq section isnt working

You Means Individual ques and ans section is not closing ?

**Comment by jsvigneshkanna** [comment]
Yes, the close/minus icon not working

**Comment by AmanJain18** [comment]
> @AmanJain18 , can you please make the text and bg color in sync with website. New blue, yellow, green colors look odd

Ya i will fix color scheme...

**Comment by AmanJain18** [comment]
> Yes, the close/minus icon not working 

Ya, i was trying to implement that functionality but i couldn't
because in pure css we can toggle any class on click 
but how to toggle tailwind css class directly.
if you know that let me know

**Comment by jsvigneshkanna** [comment]
You can check whether the class is there in the element and remove or add it right. Another way of toggling

Just try to implement it. If not I will look for the way. Am away from system, may take a day to merge
Appreciate that

**Comment by AmanJain18** [comment]
https://user-images.githubusercontent.com/89217032/200136286-f3e6b196-c6b7-4137-9c5e-467f537028e2.mp4
Is this Color Scheme Ok ?

**Comment by jsvigneshkanna** [comment]
@AmanJain18 this looks perfect

**Comment by AmanJain18** [comment]
Implemented Functionality as required...🙂

**Comment by AmanJain18** [comment]
Done the rerquired changes... Of FAQs Section...

**Comment by jsvigneshkanna** [comment]
Great @AmanJain18

**Pull request merged**
