### PR TITLE
Added Mobile Nav DropDown

### LINKED ISSUE #163: Mobile navbar with dropdown in tailwindCSS
### Description

**Need to create code for Mobile navbar with dropdown as per below image. **

- The final code should be placed under path `tailwind_components/navbars` with file name as `mobile_nav_dropdown.jsx`
- The file as to be imported to `tailwind_components/navbars/collection.js` file as per example and added to the `navbarCollections` list
- Post these process, go to components tab (components/navbars) in website and check whether the codepen is updated
- ### The navbar should be mobile responsive with hamburger menu (make it simple)

For PR reference - https://github.com/jsvigneshkanna/tailwind_ui_components/pull/76/files

For any issue while creating / importing the component code file, check below sample files
https://github.com/jsvigneshkanna/tailwind_ui_components/tree/master/tailwind_components/buttons

For icons please refer - https://heroicons.com/

### Screenshot of the tailwind component

image

### Are you taking this fetaure implementaion

No, This is up for grabs

### PR DESCRIPTION
**Pull request by streetcodec**
## Added Mobile Nav DropDown

The purpose of this Pull Request is to fix #163
### Screenshots
https://user-images.githubusercontent.com/92046906/197299711-cf0ec799-7454-4097-8bfd-294f158fb81b.png

  

##  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue conversation
- [x] I have starred the repository ⭐

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
@streetcodec 
Seems the dropdown isnt working and please add functionality to close the navbar on hamburger click

**Comment by Anuran12** [comment]
@jsvigneshkanna For working close and open system you have to add additional javascript. but there only linked javascript are working , your own script under script tag are not working. you can add another section on the codepen for javascript like the actual codepen website.

**Comment by jsvigneshkanna** [comment]
@Anuran12 , what js script should be added, can you share that. i will add that in codepen react hook itself

**Comment by jsvigneshkanna** [comment]
@Anuran12 , but you did closing of alerts right?

**Comment by Anuran12** [comment]
@jsvigneshkanna check this https://codepen.io/Zeeslag/pen/MWpLoKX

**Comment by Anuran12** [comment]
@jsvigneshkanna  see this https://codepen.io/anuran12/pen/qBYeMjd

**Comment by Anuran12** [comment]
@jsvigneshkanna now nav button is working but still dropdown  is not working.

**Comment by jsvigneshkanna** [comment]
@Anuran12 got it, will add js in codepen hook

**Comment by jsvigneshkanna** [comment]
Why flobite css and js are linked to html code?

**Comment by Anuran12** [comment]
> @Anuran12 , but you did closing of alerts right?

@jsvigneshkanna yea but I was unable to bring back the alert. remember ?

**Comment by Anuran12** [comment]
> Why flobite css and js are linked to html code?

I trited that for dropdown button  https://stackoverflow.com/questions/73247900/dropdown-list-not-working-as-expected-tailwind-css

But its not working.

**Comment by Anuran12** [comment]
@jsvigneshkanna I guess for dropdown we have to write js too

**Comment by jsvigneshkanna** [comment]
@Anuran12 ,
For now please keep this js part in hold, I will check the codepen integration first and let you know

Check other issues

**Pull request merged**
