### PR TITLE
Fixed Bugs  Issues #255

### LINKED ISSUE #255: Retain github and linkedin social icons in <900px view
### Bug Title

Retain github and linkedin social icons

### Description of BUG

Retain github and linkedin social icons in <900px view

Hide other social icons which in less than 900 px view port

### Reporduction URL of bug

https://tailwindcsscomponents.vercel.app/

### Bug Issue Type

Frontend

### Screenshot of the issue if in UI/ Document

image

### Are you taking this issue fix

No

### PR DESCRIPTION
**Pull request by AmanJain18**
## PR Title
The purpose of this Pull Request is to fix #255 

> #255 ## Bug Title
> Retain github and linkedin social icons

## How you solved
Modified tailwind.config.js -> extends -> screens

> ### Are you taking this issue fix
> YES

###  Checklist
- [x] I have Made this contribution as per the CONTRIBUTING guide in this repo
- [x] I have tested in local Environment.
- [x] I have made the fix as per issue converstaion
- [x] I have starred the repository ⭐

@jsvigneshkanna

### CODE REVIEW

**Comment by jsvigneshkanna** [comment]
Will check and let you if any changes required @AmanJain18 
Thank you!

**Comment by AmanJain18** [comment]
Okay... Hit me Up for any further changes ✌️

**Comment by AmanJain18** [comment]
> Will check and let you if any changes required @AmanJain18 
> Thank you!

Haved u checked ?

**Comment by jsvigneshkanna** [comment]
Thank you @AmanJain18 , working as expected

**Comment by AmanJain18** [comment]
> Thank you @AmanJain18 , working as expected

Please Add hacktoberfest accepted label to this pr ✌️

**Pull request merged**
